prometheus-postgres-exporter:
  fullnameOverride: recflow-postgresql-exporter
  config:
    datasource:
      host: recflow-postgresql.media.svc.cluster.local
      database: recflow
      user: admin
      passwordSecret:
        name: recflow-postgresql
        key: password
  serviceMonitor:
    enabled: true
    namespace: telemetry
    labels:
      release: prometheus-stack
