apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}
    spec:
      containers:
        - name: {{ .Values.global.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: NODE_ENV
              value: prod
            - name: CONFIG_PATH
              value: {{ .Values.configMap.mountPath }}/conf.yaml
            - name: APP_PORT
              value: "{{ .Values.app.server.port }}"
            - name: STREAMQ_URL
              value: {{ .Values.externals.streamq.url }}
            - name: STREAMQ_QSIZE
              value: "{{ .Values.externals.streamq.qsize }}"
            - name: AUTHED_URL
              value: {{ .Values.externals.authed.url }}
            - name: AUTHED_ENCKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.externals.authed.secretName }}
                  key: {{ .Values.externals.authed.enckeyKey }}
            - name: NTFY_ENDPOINT
              value: {{ .Values.externals.ntfy.endpoint }}
            - name: NTFY_TOPIC
              value: {{ .Values.externals.ntfy.topic }}
            - name: REDIS_HOST
              value: {{ .Values.app.redis.host }}
            - name: REDIS_PORT
              value: "{{ .Values.app.redis.port }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.redis.secretName }}
                  key: {{ .Values.app.redis.passwordKey }}
            - name: AMQP_HOST
              value: {{ .Values.app.rabbitmq.host }}
            - name: AMQP_PORT
              value: "{{ .Values.app.rabbitmq.port }}"
            - name: AMQP_HTTP_PORT
              value: "{{ .Values.app.rabbitmq.httpPort }}"
            - name: AMQP_USERNAME
              value: {{ .Values.app.rabbitmq.username }}
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.rabbitmq.secretName }}
                  key: {{ .Values.app.rabbitmq.passwordKey }}
            - name: PG_HOST
              value: {{ .Values.app.postgres.host }}
            - name: PG_PORT
              value: "{{ .Values.app.postgres.port }}"
            - name: PG_DATABASE
              value: {{ .Values.app.postgres.database }}
            - name: PG_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.postgres.secretName }}
                  key: {{ .Values.app.postgres.usernameKey }}
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.postgres.secretName }}
                  key: {{ .Values.app.postgres.passwordKey }}
          volumeMounts:
            - name: conf
              mountPath: {{ .Values.configMap.mountPath }}
              readOnly: true
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      volumes:
        - name: conf
          configMap:
            name: {{ .Values.configMap.name }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
