apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.globalName }}-nodeport
spec:
  selector:
    cnpg.io/cluster: {{ .Values.globalName }}
    role: primary
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
      nodePort: {{ .Values.database.nodePort }}
