apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.name }}
    spec:
      containers:
        - name: {{ .Values.global.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: CONFIG_PATH
              value: {{ .Values.configMap.mountPath }}/conf.yaml
            - name: STREAMQ_URL
              value: {{ .Values.externals.streamqUrl }}
            - name: STDL_URL
              value: {{ .Values.externals.stdlUrl }}
            - name: AUTH_URL
              value: {{ .Values.externals.authUrl }}
            - name: NTFY_ENDPOINT
              value: {{ .Values.externals.ntfyEndpoint }}
            - name: NTFY_TOPIC
              value: {{ .Values.externals.ntfyTopic }}
            - name: QUERY_SIZE
              value: "{{ .Values.externals.querySize }}"
            - name: NODE_ENV
              value: prod
          volumeMounts:
            - name: conf
              mountPath: {{ .Values.configMap.mountPath }}
              readOnly: true
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      volumes:
        - name: conf
          configMap:
            name: {{ .Values.configMap.name }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
