subsChzzkChanIds: []
subsSoopUserIds: []

chzzkMinUserCnt: 0
chzzkMinFollowerCnt: 0
soopMinUserCnt: 0
soopMinFollowerCnt: 0

chzzkTags: []
chzzkKeywords: []
soopCateNoList: []

excludedChzzkCates: []
excludedChzzkTags: []
excludedChzzkKeywords: []

allowedSoopUserIds: []
excludedSoopUserIds: []

allowedChzzkChanNames: []
excludedChzzkChanNames: []
excludedChzzkChanIds: []
