global:
  name: stmgr
  namespace: media

image:
  repository: harbor.rwiv.xyz/private/stmgr
  tag: 0.1.1
  pullSecret: image-pull-secret

affinity: {}
tolerations:
  - key: cpu
    operator: Exists

externals:
  ntfyEndpoint: http://ntfy.common.svc.cluster.local
  ntfyTopic: stmgr
  stdlUrl: http://webhook-eventsource-svc.media.svc.cluster.local:12000/stdl
  authUrl: http://authed-server.media.svc.cluster.local
  streamqUrl: http://streamq.media.svc.cluster.local
  querySize: "1000"

configMap:
  name: stmgr-conf
  mountPath: /app/conf

subscribeChannelIds: []
subscribeUserIds: []
minUserCnt: 0
minFollowerCnt: 0
tags: []
keywords: []
soopCateNoList: []
ignoredCategories: []
ignoredTags: []
ignoredKeywords: []
whiteListChannels: []
ignoredChannels: []
whiteListUserIds: []
ignoredUserIds: []
