global:
  name: stmgr
  namespace: media

image:
  repository: harbor.rwiv.xyz/private/stmgr
  tag: 0.1.0
  pullSecret: image-pull-secret

affinity: {}
tolerations:
  - key: cpu
    operator: Exists

externals:
  ntfyEndpoint: http://ntfy.common.svc.cluster.local
  ntfyTopic: stmgr
  streamqUrl: http://streamq.media.svc.cluster.local
  stdlUrl: http://webhook-eventsource-svc.media.svc.cluster.local:12000/stdl
  authUrl: http://authed-server.media.svc.cluster.local

configMap:
  name: stmgr-conf
  mountPath: /app/conf

subscribeChannelIds: []
minUserCnt: 100
minFollowerCnt: 1000
tags: []
keywords: []
sufficientTags: []
ignoredCategories: []
ignoredTags: []
ignoredKeywords: []
whiteListChannels: []
ignoredChannels: []
