global:
  name: stmgr
  namespace: media

image:
  repository: harbor.rwiv.xyz/private/stmgr
  tag: 0.1.5
  pullSecret: image-pull-secret

affinity: {}
tolerations:
  - key: cpu
    operator: Exists

externals:
  streamq:
    url: http://streamq.media.svc.cluster.local
    qsize: 1000
  stdl:
    url: http://webhook-eventsource-svc.media.svc.cluster.local:12000/stdl
  authed:
    url: http://authed-server.media.svc.cluster.local
    secretName: authed-app
    enckeyKey: enckey
  ntfy:
    endpoint: http://ntfy.common.svc.cluster.local
    topic: stmgr

configMap:
  name: stmgr-conf
  mountPath: /app/conf

subsChzzkChanIds: []
subsSoopUserIds: []

chzzkMinUserCnt: 0
chzzkMinFollowerCnt: 0
soopMinUserCnt: 0
soopMinFollowerCnt: 0

chzzkTags: []
chzzkKeywords: []
soopCateNoList: []

excludedChzzkCates: []
excludedChzzkTags: []
excludedChzzkKeywords: []

allowedSoopUserIds: []
excludedSoopUserIds: []

allowedChzzkChanNames: []
excludedChzzkChanNames: []
excludedChzzkChanIds: []
